// frontend-types-entityid: branded EntityId override.
// frontend-types-discriminated: discriminated server-event union.
// frontend-types-entity-response: discriminated EntityResponse union.
//
// All app code imports from this module, NEVER from `./types` directly.
//
// `./types` is auto-generated by `just _gen-types` from the Pydantic wire
// models. pydantic2ts walks top-level BaseModel subclasses only; the
// `Entity.Model` / `Character.Model` / `Scene.Model` / `Campaign.Model`
// nested classes (now the canonical wire shape — see
// specs/entity-model.md `entity-model-canonical`) cannot be picked up
// that way, so they're hand-rolled here and must be kept in sync with
// the backend manually.

import type {
  MessageAccepted as _MessageAccepted,
  MessageRequest as _MessageRequest,
} from './types';

// frontend-types-entityid: brand the opaque id type so it cannot be
// confused with arbitrary strings at the type level.
export type EntityId = string & { readonly _brand: 'EntityId' };

// Helper to coerce raw strings into branded EntityId at the trust
// boundary (i.e. when reading from the wire). After this, the type
// system enforces the brand throughout the app.
export const asEntityId = (s: string): EntityId => s as EntityId;

// Hand-rolled mirrors of the backend `Entity.Model` subclasses. These
// ARE the canonical wire shape — there are no parallel `*Response`
// types on the backend (per entity-model-canonical).

export interface CharacterModel {
  type: 'character';
  id: EntityId;
  name: string;
  body: string;
  owner: 'user' | 'stub' | 'npc';
}

export interface SceneModel {
  type: 'scene';
  id: EntityId;
  name: string;
  body: string;
  character_ids: EntityId[];
}

export interface CampaignModel {
  name: string;
  default_scene_id: EntityId | null;
}

// frontend-types-entity-response: discriminated union returned by
// `GET /api/campaigns/{cid}/entities/{eid}`. The dispatch surface for
// `EntityPanel`.
export type EntityModel = SceneModel | CharacterModel;

// Phase 1 transitional aliases. Existing FE code (workspace, useEntity,
// EntityPanel, widgets) uses the legacy `*Response` names. These aliases
// keep that code compiling; Phase 2b renames the call sites to the
// `*Model` names and drops these aliases.
export type CharacterResponse = CharacterModel;
export type SceneResponse = SceneModel & {
  // Derived field exposed on the legacy wire shape; the new Scene.Model
  // does not carry it (the FE computes it from `character_ids` +
  // per-character owner). Kept here so Phase 1 widget code compiles.
  player_character_ids: EntityId[];
};
export type CampaignResponse = CampaignModel;
export type EntityResponse = SceneResponse | CharacterResponse;

export interface MessageRequest extends Omit<_MessageRequest, 'sender_id'> {
  sender_id: EntityId;
}

export interface MessageAccepted extends Omit<_MessageAccepted, 'scene_id'> {
  scene_id: EntityId;
}

// Wire shape of items in the `GET /api/campaigns/{cid}/scenes/{sid}/messages`
// response list. Mirrors the nested `sidestage.message.Message.Model`
// Pydantic class.
export interface MessageModel {
  scene_id: EntityId;
  index: number;
  sender_id: EntityId;
  body: string;
}

// SSE/WS event payload for `entity_changed`. Mirrors
// `sidestage.events.EntityChanged` — a `@dataclass`, not a Pydantic
// model, so pydantic2ts cannot pick it up.
export interface EntityChangedEvent {
  entity_id: EntityId;
  attributes: string[];
}

// frontend-types-discriminated: ServerEvent union for WS event payloads.
// Today only one variant exists; the union is exhaustive on `type`.
export type ServerEvent = EntityChangedEvent & { type: 'entity_changed' };

// frontend-state-chatmessage: rendered message with the sender resolved
// against the registry cache. Produced by the Scene widget's per-message
// sender-resolution step; consumed by MessageList / MessageItem.
export interface ChatMessage {
  scene_id: EntityId;
  index: number;
  sender: CharacterResponse;
  body: string;
}
