// frontend-types-entityid: branded EntityId override.
// frontend-types-discriminated: discriminated server-event union.
// frontend-types-entity-response: discriminated EntityResponse union.
//
// All app code imports from this module, NEVER from `./types` directly.
//
// `./types` is auto-generated by `just _gen-types` from the Pydantic wire
// models. pydantic2ts walks top-level BaseModel subclasses only; the
// `Entity.Model` / `Character.Model` / `Scene.Model` / `Campaign.Model`
// nested classes (now the canonical wire shape — see
// specs/entity-model.md `entity-model-canonical`) cannot be picked up
// that way, so they're hand-rolled here and must be kept in sync with
// the backend manually.

// frontend-types-entityid: brand the opaque id type so it cannot be
// confused with arbitrary strings at the type level.
export type EntityId = string & { readonly _brand: 'EntityId' };

// Helper to coerce raw strings into branded EntityId at the trust
// boundary (i.e. when reading from the wire). After this, the type
// system enforces the brand throughout the app.
export const asEntityId = (s: string): EntityId => s as EntityId;

// Hand-rolled mirrors of the backend `Entity.Model` subclasses. These
// ARE the canonical wire shape — there are no parallel `*Response`
// types on the backend (per entity-model-canonical).

export interface CharacterModel {
  type: 'character';
  id: EntityId;
  name: string;
  body: string;
  owner: 'user' | 'stub' | 'npc';
}

export interface SceneModel {
  type: 'scene';
  id: EntityId;
  name: string;
  body: string;
  character_ids: EntityId[];
}

export interface CampaignModel {
  name: string;
  default_scene_id: EntityId | null;
}

// frontend-types-entity-response: discriminated union returned by
// `GET /api/campaigns/{cid}/entities/{eid}`. The dispatch surface for
// `EntityPanel`.
export type EntityModel = SceneModel | CharacterModel;

// Phase 1 transitional aliases. Existing FE code (workspace, useEntity,
// EntityPanel, widgets) uses the legacy `*Response` names. These aliases
// keep that code compiling; Phase 2b renames the call sites to the
// `*Model` names and drops these aliases.
export type CharacterResponse = CharacterModel;
export type SceneResponse = SceneModel & {
  // Derived field exposed on the legacy wire shape; the new Scene.Model
  // does not carry it (the FE computes it from `character_ids` +
  // per-character owner). Kept here so Phase 1 widget code compiles.
  player_character_ids: EntityId[];
};
export type CampaignResponse = CampaignModel;
export type EntityResponse = SceneResponse | CharacterResponse;

// Wire shape of a single message inside a Scene. The BE `Message.Model`
// carries only `sender_id` and `body` (per `specs/message.md` — identity
// is positional, the message at index N in scene S's `messages`). The
// FE-side `MessageModel` additionally carries `scene_id` and `index`,
// synthesised from the parent scene id + position when the registry
// ingests a `subscribed` reply or applies a `ListDelta`. This keeps
// MessageList/MessageItem's positional keys stable without rippling
// through every consumer.
export interface MessageModel {
  scene_id: EntityId;
  index: number;
  sender_id: EntityId;
  body: string;
}

// frontend-types-delta-list: payload shape for a collection-attribute
// change on `entity_changed`. Splice semantics: replace `len` items at
// `start` with `items`. `start === -1` short-circuits to push-at-end
// (per `specs/events.md#events-attribute-deltas`).
export interface ListDelta {
  start: number;
  len: number;
  items: unknown[];
}

// frontend-types-delta-scalar: payload shape for a scalar-attribute
// change. The new value of the attribute.
export interface ScalarDelta {
  value: unknown;
}

export type AttributeDelta = ListDelta | ScalarDelta;

// frontend-types-entity-action: client → server frame for invoking an
// `@action`-decorated method on any entity. The server resolves the
// entity, dispatches the action, and replies with a matching `ack` or
// `error` keyed by `request_id`.
export interface EntityActionFrame {
  op: 'entity_action';
  entity_id: EntityId;
  action: string;
  kwargs: Record<string, unknown>;
  request_id: string;
}

// frontend-types-discriminated: ServerEvent union for WS frames the
// server pushes to the client (per `specs/events.md#events-subscription`).
// Discriminated on `op`.
export interface SubscribedEvent {
  op: 'subscribed';
  request_id: string;
  states: Array<{ entity_id: string; model: unknown }>;
}

export interface EntityChangedEvent {
  op: 'entity_changed';
  entity_id: string;
  attributes: string[];
  deltas?: Record<string, AttributeDelta>;
}

export interface AckEvent {
  op: 'ack';
  request_id: string;
}

export interface ErrorEvent {
  op: 'error';
  request_id: string;
  code: string;
  message: string;
}

export type ServerEvent =
  | SubscribedEvent
  | EntityChangedEvent
  | AckEvent
  | ErrorEvent;

// frontend-state-chatmessage: rendered message with the sender resolved
// against the registry cache. Produced by the Scene widget's per-message
// sender-resolution step; consumed by MessageList / MessageItem.
export interface ChatMessage {
  scene_id: EntityId;
  index: number;
  sender: CharacterResponse;
  body: string;
}
