// frontend-types-generated: This file is the wire-format type surface.
//
// SPEC NOTE: spec frontend-types-generated says this is auto-generated by
//   `uv run pydantic2ts --module sidestage.server --output frontend/src/types.ts`.
// In this implementation round it is HAND-WRITTEN to mirror the current
// Pydantic models in src/sidestage/{server,scene,campaign,character,actor,
// message,entity}.py. A subsequent pydantic2ts invocation will overwrite
// this file; the hand-written shape MUST stay in sync until then.
//
// All app code imports from `./types_ext`, NOT from this file directly.

export type EntityId = string;

export type EntityType = 'character' | 'scene' | 'entity';

// Mirror of sidestage.entity.Entity.Model
export interface EntityModel {
  id: EntityId;
  name: string;
  type: EntityType;
  body: string;
}

// Mirror of sidestage.character.Character.Model
export interface CharacterModel extends EntityModel {
  type: 'character';
  owner: 'user' | 'npc' | 'stub';
}

// Mirror of sidestage.scene.SceneResponse
export interface SceneResponse {
  id: EntityId;
  name: string;
  character_ids: EntityId[];
  player_character_ids: EntityId[];
}

// Mirror of sidestage.campaign.CampaignResponse
export interface CampaignResponse {
  name: string;
  default_scene_id: EntityId | null;
}

// Mirror of sidestage.message.Message.Model
export interface MessageModel {
  scene_id: EntityId;
  index: number;
  sender_id: EntityId;
  body: string;
}

// Mirror of sidestage.server.MessageRequest
export interface MessageRequest {
  sender_id: EntityId;
  body: string;
}

// Mirror of sidestage.server.MessageAccepted
export interface MessageAccepted {
  scene_id: EntityId;
  index: number;
}

// Mirror of sidestage.events.EntityChanged (SSE wire shape — see
// `events-subscription` in specs/events.md).
export interface EntityChangedEvent {
  entity_id: EntityId;
  attributes: string[];
}
