// frontend-types-entityid: branded EntityId override.
// frontend-types-discriminated: discriminated server-event union.
// frontend-types-entity-response: discriminated EntityResponse union.
//
// All app code imports from this module, NEVER from `./types` directly.
//
// `./types` is auto-generated by `just _gen-types` from the Pydantic wire
// models; this module brands its id-bearing fields with the opaque
// `EntityId` type and supplies the shapes pydantic2ts cannot surface
// (nested Pydantic models like `Message.Model`, plain dataclasses like
// `EntityChanged`).

import type {
  CampaignResponse as _CampaignResponse,
  CharacterResponse as _CharacterResponse,
  MessageAccepted as _MessageAccepted,
  MessageRequest as _MessageRequest,
  SceneResponse as _SceneResponse,
} from './types';

// frontend-types-entityid: brand the opaque id type so it cannot be
// confused with arbitrary strings at the type level.
export type EntityId = string & { readonly _brand: 'EntityId' };

// The auto-generated `type` discriminators are optional (`type?: "scene"`)
// because their Pydantic counterparts have defaults. Override to required
// here so the discriminated union dispatch narrows correctly.

export interface CharacterResponse extends Omit<_CharacterResponse, 'id' | 'type'> {
  type: 'character';
  id: EntityId;
}

export interface SceneResponse
  extends Omit<_SceneResponse, 'id' | 'type' | 'character_ids' | 'player_character_ids'> {
  type: 'scene';
  id: EntityId;
  character_ids: EntityId[];
  player_character_ids: EntityId[];
}

export interface CampaignResponse extends Omit<_CampaignResponse, 'default_scene_id'> {
  default_scene_id: EntityId | null;
}

export interface MessageRequest extends Omit<_MessageRequest, 'sender_id'> {
  sender_id: EntityId;
}

export interface MessageAccepted extends Omit<_MessageAccepted, 'scene_id'> {
  scene_id: EntityId;
}

// frontend-types-entity-response: discriminated union returned by
// `GET /api/campaigns/{cid}/entities/{eid}`. The dispatch surface for
// `EntityPanel`.
export type EntityResponse = SceneResponse | CharacterResponse;

// Hand-rolled wire types not surfaced by pydantic2ts.

// Wire shape of items in the `GET /api/campaigns/{cid}/scenes/{sid}/messages`
// response list. Mirrors the nested `sidestage.message.Message.Model`
// Pydantic class (pydantic2ts walks top-level BaseModel subclasses, not
// nested ones).
export interface MessageModel {
  scene_id: EntityId;
  index: number;
  sender_id: EntityId;
  body: string;
}

// SSE event payload for `entity_changed`. Mirrors
// `sidestage.events.EntityChanged` — a `@dataclass`, not a Pydantic
// model, so pydantic2ts cannot pick it up.
export interface EntityChangedEvent {
  entity_id: EntityId;
  attributes: string[];
}

// Helper to coerce raw strings into branded EntityId at the trust
// boundary (i.e. when reading from the wire). After this, the type
// system enforces the brand throughout the app.
export const asEntityId = (s: string): EntityId => s as EntityId;

// frontend-types-discriminated: ServerEvent union for SSE event payloads.
// Today only one variant exists; the union is exhaustive on `type`.
export type ServerEvent = EntityChangedEvent & { type: 'entity_changed' };
